### ISSUE TITLE
Is there a way I can display the 3D skin images on my website?

### ISSUE THREAD

**Issue by TomLewis** [MineSkin/mineskin.org#1]
Hi! 
Is there any way I can use your JS that displays your skins in 3D to rotate around skins on my website?
I found https://skinrender.ga but its super, super laggy in firefox where as mineskin.org 3D animation is smooth.

**Comment by InventivetalentDev** [comment]
MineSkin was created to generate skin textures, not to display them on websites.
That's actually why I created SkinRender :P (which is also used by MineSkin, btw)

If you're having issues with SkinRender, feel free to create an issue on its repository https://github.com/InventivetalentDev/SkinRender/issues

**Comment by TomLewis** [comment]
Thats what I assumed, I just didnt get why skins works completely fine in firefox in mineskin.org, but on SkinRender they are so laggy it nearly crashes the browser.

Ok I think its just Firefox on OSX that its super laggy, on my windows box it seems fine.
