### ISSUE TITLE
Invalid URLs in footer

### ISSUE THREAD

**Issue by Andre601** [MineSkin/mineskin.org#11]
## What steps will reproduce the problem?  
1. Go to https://mineskin.org
2. Scroll down to the footer
3. Click on either `Custom Skins Plugin` or `Custom Blocks Plugin`

## What were you expecting to happen? What happened instead?  
The Links should've forwarded me to their respective pages, but I received 404 errors instead.

**Comment by Andre601** [comment]
That bot should imo be removed considering that 99% of "stale" issues are mainly because of no responses by the maintainer of the project (You inventivetalent)

**Comment by InventivetalentDev** [comment]
Considering I'm seeing this now, the bot seems to be doing its job just fine :P  
I'm also aware that I'm the maintainer, thanks for the reminder though.  
Links work fine again.
