### ISSUE TITLE
delay request spamming console & unable to generate

### ISSUE THREAD

**Issue by ReinWD** [MineSkin/mineskin.org#17]
## What steps will reproduce the problem?  
1. open website using chrome
2. press F12 
3. watch "Network" tab

## What were you expecting to happen? What happened instead?  
delay request is spamming.
and timeout is not responding.
![image](https://user-images.githubusercontent.com/22649596/106896391-74c19e00-672c-11eb-801f-8f74b85107ad.png)
![image](https://user-images.githubusercontent.com/22649596/106896489-9589f380-672c-11eb-936d-1f5614a3f93c.png)
it can build up to 30,000+ requests, causing CPU usage raise and I can't use the generate button.

**Comment by InventivetalentDev** [comment]
couldn't get this to happen for me, but I made some changes to caching so it should properly load the current delay info now

**Comment by ReinWD** [comment]
some more infomation:
I use it to generate texture value and signature from skin in namemc.com.
I pasted "https://namemc.com/texture/590f6b487b94d5ce.png" into it, c-v value & signature, and pressed "back" button on my browser many times(because I want to back to home page and generate a new one). But the second one was failed (reason fogot, maybe some issue with my network or issue with back button) and it tells me that i should wait 5 secs until next requese. But then the delay stucked at 4.082999... . I tried to clear my cookies but don't work. Finally I removed the "disabled" label on generate button and it works. 

Thanks for your amazing work.

**Comment by ReinWD** [comment]
and it may not an issue with cache. I tried to disable disk cache in my dev tool, but it was still spamming my request. It seems to have many requests with similar(maybe equal) return val "4.082999...". That 4.082999...  parameter may causing a backend loop.

**Comment by ReinWD** [comment]
![image](https://user-images.githubusercontent.com/22649596/106975301-40cc9400-6791-11eb-9827-526f30ecdc1a.png)
successfully reproduced by multi-clicking generate button and using back while loading new page.

[mineskin.org.har.zip](https://github.com/MineSkin/mineskin.org/files/5929436/mineskin.org.har.zip)

full request information here.

**Comment by InventivetalentDev** [comment]
made some more changes and doesn't seem to happen anymore
