### ISSUE TITLE
Status Tracker unavailable

### ISSUE THREAD

**Issue by Th3Shadowbroker** [MineSkin/mineskin.org#18]
## What steps will reproduce the problem?  
1. Navigate to https://status.mineskin.org/

## What were you expecting to happen? What happened instead?  
UptimeRobot displays a 404 page instead of the service stats.

**Comment by InventivetalentDev** [comment]
Oh wow... apparently they changed their plan to only allow one public status page ._.

**Comment by InventivetalentDev** [comment]
Changed it to redirect to the [main status page](https://status.inventivetalent.org/778205491)

**Comment by James103** [comment]
Both `https://status.inventivetalent.org/778205491` and `https://status.inventivetalent.org` return HTTP 404 errors on load for me.

**Comment by InventivetalentDev** [comment]
Ah now they changed it to no custom domains at all, great.
