### ISSUE TITLE
Microsoft accounts

### ISSUE THREAD

**Issue by AwesomeKalin** [MineSkin/mineskin.org#22]
Eventually, the site will stop working as all Mojang accounts will be transitioned to Microsoft accounts. The mineskin project will have to support Microsoft accounts before the transition finishes. The solution would be to have a login option to Microsoft and then it uses tokens to authenticate afterwards

**Comment by InventivetalentDev** [comment]
yep ^^ 
![image](https://user-images.githubusercontent.com/6525296/120931274-22e84f00-c6f1-11eb-826a-918af7c9e16f.png)

https://mineskin.org/account
