### ISSUE TITLE
"Sign in with Microsoft" button does not work for Edge (Chromium in general)

### ISSUE THREAD

**Issue by Andre601** [MineSkin/mineskin.org#25]
When trying to login using the "Sign in with Microsoft" button does absolutely nothing happen.
No response, no popup, nothing.

There are also no warnings in the browser console, nor any other indicators of a failure. The only guess I have is, that the action that should be triggered (`startMicrosoftFlow()`) doesn't exist or is perhaps misspelt.

I would appreciate, if a fix could be made, as you otherwise lose at least one account because of the migration.

**Comment by InventivetalentDev** [comment]
> as you otherwise lose at least one account because of the migration   

whoa, no need to threaten about what's probably just a cache issue lol

**Comment by Andre601** [comment]
> whoa, no need to threaten about what's probably just a cache issue lol

Not really a threat but more a fact because I assume with the migration would you need to re-login to update the info.

I admit I didn't spell it right here, so sorry about that.

**Comment by Andre601** [comment]
Also, maybe make those boxes disappear after some time?

![image](https://user-images.githubusercontent.com/11576465/130447199-9d220ef6-d503-49db-a74d-3afa7ea6f603.png)

Because it doesn't disappear for me. (Login works btw, thanks for the fix)
