### ISSUE TITLE
[Feature suggestion] Taterzens skin command

### ISSUE THREAD

**Issue by samolego** [MineSkin/mineskin.org#26]
Hi there!

First off, thanks for the great api! :)

Mineskin website does already have a built-in citizens command for setting skin.
https://github.com/MineSkin/mineskin.org/blob/b16feb623c6573d282760973412c0bccca2fc20b/pages/view.html#L197-L210

I'm creator of serverside mod [`Taterzens`](https://www.curseforge.com/minecraft/mc-mods/taterzens) ([github](https://github.com/samolego/Taterzens)), a fabric / forge NPC mod, which has a support to fetch skins from mineskin already. I was wondering if you could add a field with skin command for my mod as well?

Command looks like the following one
```
/npc edit skin https://minesk.in/807171128
```
So the code would be sth. like this (just copied & modified existing Citizens code)

```html
<div class="row card-panel">
    <h5 id="taterzens">Taterzens Skin Command</h5>
    <div class="col s12">
        <div>
            <div class="row">
                <div class="input-field col s12">
                    <label for="taterzensCommand">Taterzens /npc edit skin Command</label>
                    <textarea style="min-height: 10px;max-width:100%;" id="taterzensCommand" class="materialize-textarea" readonly>/npc edit skin https://minesk.in/{{ skin.id }}</textarea>
                    <button class="btn tooltipped" data-clipboard-target="#taterzensCommand"><i class="fa fa-clipboard" aria-hidden="true"></i> Copy</button>
                </div>
            </div>
        </div>
    </div>
</div>
```

I know users can already just copy the citizens url and then write command on their own, but I'd be glad if you could add this one as well, in case you don't feel like it adds too much clutter :). Thanks.

**Comment by InventivetalentDev** [comment]
I'll do some restructuring to combine all plugin/mod stuff into a single card and then add yours! :)

**Comment by samolego** [comment]
Thank you so much!
