### ISSUE TITLE
Re-add a way to see own generated skins

### ISSUE THREAD

**Issue by Andre601** [MineSkin/mineskin.org#28]
**Is your feature request related to a problem? Please describe.**
Due to the site now loading new skins while scrolling is it impossible to reach the section of the skins you yourself generated. That coupled with the fact that private skins won't be visible in the gallery itself makes it impossible to find own, privately generated skins anymore.

**Describe the solution you'd like**
There should be a way to view and access your own generated skins. Perhaps with a separate tab?

**Describe alternatives you've considered**
There isn't really one outside of searching through the gallery which, again, only depicts public skins and not those that you created privately.

**Additional context**
I recently made a skin and encountered a random loading issue of the info screen, which made it impossible for me to actually get the skin-info (i.e. command) I needed.

While the loading issue has been fixed thanks through reloading does it show a core issue that you can face anytime in the future.

Here's a screenshot of the stuck loading window:
![image](https://user-images.githubusercontent.com/11576465/139527606-eaae8a75-4998-436e-9388-2ba36a5a6c8c.png)

**Comment by InventivetalentDev** [comment]
I'll look into adding that section again! Please make a separate issue for the loading issues though :)

**Comment by Andre601** [comment]
> I'll look into adding that section again! Please make a separate issue for the loading issues though :)

The loading issue was a one-time thing and I don't have steps to reliably reproduce it, so not sure if it's worth to make an issue for it.

**Comment by Andre601** [comment]
Hey, uh so.... The toggle to see the skins you uploaded is nice, but I noticed that you can't see the detailed info when clicking it?
Like there is no window opening when you click the skin.

Also, another minor problem is that even tho all skins are loaded, the site is still applying that infinite scroll logic from the main gallery, which feels a bit out of place.
Hope you can fix those issues too.

Appreciate the work you've done so far.
