### ISSUE TITLE
Skins randomly changing to other skins

### ISSUE THREAD

**Issue by Khrystyian** [MineSkin/mineskin.org#29]
## What steps will reproduce the problem?  
1. Download any skin from mineskin.org
2. Apply that skin to any NPC.
3. Wait for some time and see it will update to random one.

## What were you expecting to happen? What happened instead?  
The skin that should appear is but when using it from mineskin, a totally random skin appears, for example I had a Elizabeth skin downloaded from mineskin.org and two days later I check and skin updated to a dark random skin. No changes were made manually after the Elizabeth NPC skin.

**Comment by InventivetalentDev** [comment]
more likely an issue with whatever NPC plugin you're using

**Comment by Andre601** [comment]
Most important: What NPC plugin do you actually use and how do you apply the texture? You're mentioning "downloading" a skin from the site. No proper NPC plugin should require this at all.

**Comment by Khrystyian** [comment]
False alarm guys, was an issue with my Launcher. (Lol yes, the launcher). Updated it with the fixes from the most recent security issue and it was fixed. :)
