### ISSUE TITLE
Support new textures.

### ISSUE THREAD

**Issue by Andre601** [MineSkin/mineskin.org#3]
First of all: I hope I ask this in the right place. If not feel free to move it to the right issue tracker (if there is one).

I want to suggest to implement support for the newer textures of MC, which allow you to have separate textures for your left and right arms and legs.
Unfortunately does mineskin not support those textures. When uploading one of those textures (such as [this one here](https://user-images.githubusercontent.com/11576465/66818077-0b1cef80-ef3d-11e9-960d-9e67554133cf.png) for example) does mineskin not recognize it as a valid, supported Skin.
This can (and will) limit users in making a skin.

**Comment by InventivetalentDev** [comment]
Not sure why it's not working properly for you, but MineSkin does support those textures just fine.  
In fact, I just generated a skin with your linked image: https://mineskin.org/1288799917

**Comment by Andre601** [comment]
Hm... weird.
Perhaps a small bug? I just remember that the "Generate!" button was greyed out (not highlighted) when I uploaded the skin.
