### ISSUE TITLE
Option to save generated skins under an account

### ISSUE THREAD

**Issue by Andre601** [MineSkin/mineskin.org#33]
**Is your feature request related to a problem? Please describe.**
Right now does the website seem to store the skins you yourself generated using cookies(?)
This has the unwanted downside that whenever you f.e. clear your browser history, which may include cookies, or switch browsers, you will lose all the skins you've generated, which especially for private ones makes them impossible to recover.

**Describe the solution you'd like**
Maybe offer an option to sign in with a Mojang/Microsoft account but not to allow the site to use the account for skin generation but simply as a way to associate skins with it so that you can always login and find the skins you generated.

**Describe alternatives you've considered**
Not clearing cookies or staying with your browser, which both aren't optimal for different reasons.

**Additional context**
I regularly clear out my browser history to improve overall performance (And storage space used by all the cached data) and this will always cause me to lose skins I may want to re-use at a later point in time.

Having a more permanent way to keep generated skins associated with you would be really awesome.

**Comment by InventivetalentDev** [comment]
done! you can now sign in at https://mineskin.org/account and it'll store your generated skins :)
