### ISSUE TITLE
Remove Account

### ISSUE THREAD

**Issue by HacksLua** [MineSkin/mineskin.org#34]
Hello, how remove my account?
![image](https://user-images.githubusercontent.com/20579067/175996096-03f88389-ed32-481f-b69a-c22746e4b489.png)
I'am remove in microsoft  https://account.live.com/consent/Manage?fref=home.drawers.privacy.app-and-services
But my skins keep changing...
HacksLua

**Comment by InventivetalentDev** [comment]
login to the Minecraft account you registered on mineskin.org and delete it.

**Comment by HacksLua** [comment]
> login to the Minecraft account you registered on mineskin.org and delete it.

In launcher? Or microsoft?

UPD:
I deleted and restored the account, nothing has changed (microsoft)

**Comment by InventivetalentDev** [comment]
https://mineskin.org/account/minecraft

**Comment by HacksLua** [comment]
Nice, thank you 👍
