### ISSUE TITLE
Apikey generate is not working 

### ISSUE THREAD

**Issue by sebastianjnuwu** [MineSkin/mineskin.org#38]
I'm trying to generate a Key for myself to use in the skin restore plugin, but unfortunately the site doesn't cooperate to generate this Key!

![Screenshot_20230606-121314](https://github.com/MineSkin/mineskin.org/assets/101356556/8da8f3f4-42d7-4ea2-8beb-0a6211a40748)

**Comment by sebastianjnuwu** [comment]
When I select to create a Key or try to login it does not go at all I need urgent help to get the Key for the spigot SkinRestore plugin

**Comment by InventivetalentDev** [comment]
try again pls, there were some issues with login recently
