### ISSUE TITLE
Infinitely Checking if the site connection is secure

### ISSUE THREAD

**Issue by GeorgeV220** [MineSkin/mineskin.org#39]
the page never loads it just shows cloudflare Checking if the site connection is secure
## What steps will reproduce the problem?  
1. Just go to https://mineskin.org/account and try to login or add a new minecraft account

## What were you expecting to happen? What happened instead?  
The account page to load

**Comment by InventivetalentDev** [comment]
should be fixed

**Comment by GeorgeV220** [comment]
Thank you very much!!
