### ISSUE TITLE
Add an ID field next to Texture Data, Texture Signature, etc

### ISSUE THREAD

**Issue by mxs42** [MineSkin/mineskin.org#7]
**Is your feature request related to a problem? Please describe.**
I created an integration that allows to set any skin from MineSkin ingame by its ID so players can go to mineskin.org, find any skin they like and copy its ID to paste it in command.
It's pretty much obvious where to find skin ID since it is located above the preview but when you generate a new skin using Minecraft Username, MineSkin displays that _username_ instead of ID, so users can only locate that ID from URL.

**Describe the solution you'd like**
For consistency I suggest either to display ID even when you generate a skin using Minecraft Username, or to completely move ID to its own field. 
![00059_firefox](https://user-images.githubusercontent.com/34000717/77332137-b1fa8880-6d32-11ea-898d-008e84d8ab72.jpg)

**Additional context**
Actually this issue is a kind of nitpicking I guess, just some of my players asked me about it.

**Comment by MeinLiX** [comment]
Good Work

**Comment by mxs42** [comment]
Live, I guess this can be closed now.
Thank you @InventivetalentDev!
