### ISSUE TITLE
The problem of skins display on the site

### ISSUE THREAD

**Issue by MeinLiX** [MineSkin/mineskin.org#9]
I faced a problem on your site about the display of minecraft skins. 
**1.You mistaked a left hand for a right hand while displaying skin on the site.**
It displays properly on the other sites where I can upload skins.
 The attached screenshot displays our minecraft server that uses your site for skins integration.
( It's not ad :D)
![proof](https://user-images.githubusercontent.com/25272773/77421081-db1f2580-6dd3-11ea-8a27-b358e5e6cd41.png)

**Comment by InventivetalentDev** [comment]
https://github.com/InventivetalentDev/MineRender/issues/27

**Comment by InventivetalentDev** [comment]
Fix should be live on minerender! :)
